import 'package:hive_flutter/hive_flutter.dart';

part 'scan_record.g.dart'; // generated by build_runner

/// Hive type IDs must be unique across your entire app.
/// ScanRecord = 0, ScanMode = 1
@HiveType(typeId: 0)
class ScanRecord extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String rawText; // text extracted by OCR

  @HiveField(2)
  final String aiResult; // markdown response from Claude

  @HiveField(3)
  final ScanMode mode; // which AI mode was used

  @HiveField(4)
  final DateTime createdAt;

  @HiveField(5)
  final String? imageFileName; // optional — original image name for display

  ScanRecord({
    required this.id,
    required this.rawText,
    required this.aiResult,
    required this.mode,
    required this.createdAt,
    this.imageFileName,
  });

  /// Convenience factory — generates id and timestamp automatically
  factory ScanRecord.create({
    required String rawText,
    required String aiResult,
    required ScanMode mode,
    String? imageFileName,
  }) {
    return ScanRecord(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      rawText: rawText,
      aiResult: aiResult,
      mode: mode,
      createdAt: DateTime.now(),
      imageFileName: imageFileName,
    );
  }

  /// Short preview of OCR text for the history list
  String get textPreview {
    const maxLength = 80;
    if (rawText.length <= maxLength) return rawText;
    return '${rawText.substring(0, maxLength)}...';
  }

  /// Short preview of AI result for the history list
  String get aiPreview {
    final cleaned = aiResult.replaceAll(RegExp(r'[#*`]'), '').trim();
    const maxLength = 100;
    if (cleaned.length <= maxLength) return cleaned;
    return '${cleaned.substring(0, maxLength)}...';
  }

  @override
  String toString() =>
      'ScanRecord(id: $id, mode: ${mode.label}, chars: ${rawText.length})';
}

// ─── ScanMode enum ──────────────────────────────────────────────────────────

/// The AI analysis mode selected by the user.
/// Stored in Hive so history shows which mode was used.
@HiveType(typeId: 1)
enum ScanMode {
  @HiveField(0)
  summarize,

  @HiveField(1)
  translate,

  @HiveField(2)
  qa,
}

/// Extension so we can get display labels and prompts in one place
extension ScanModeX on ScanMode {
  String get label => switch (this) {
        ScanMode.summarize => 'Summarize',
        ScanMode.translate => 'Translate',
        ScanMode.qa        => 'Q & A',
      };

  String get emoji => switch (this) {
        ScanMode.summarize => '📝',
        ScanMode.translate => '🌐',
        ScanMode.qa        => '❓',
      };

  /// The prompt sent to Claude — all prompts live here, not scattered in screens
  String buildPrompt(String ocrText) => switch (this) {
        ScanMode.summarize =>
          'Summarize the following document in clear bullet points. '
          'Highlight the most important information:\n\n$ocrText',
        ScanMode.translate =>
          'Detect the language of the following text, translate it to English, '
          'then provide a brief summary:\n\n$ocrText',
        ScanMode.qa =>
          'Analyze the following document and answer: '
          'Who is involved? What is it about? When? Where? Any action items?\n\n$ocrText',
      };
}